import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Link from "next/link";
import styles from "./styles.module.css";

const roboto = Roboto({ weight: ["300", "500"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className={styles.container}>
          <span style={{ marginRight: "10px" }}>Root layout</span>
          <Link href="/users">user</Link> <Link href="/posts">posts</Link>{" "}
          <Link href="/parallel">parallel</Link>
        </div>
        {children}
      </body>
    </html>
  );
}
